const storageParticipants = 'cht-subs-csv'
const storageWinners = 'cht-subs-winners'
const storageNotWinner = 'cht-subs-not'
const storageSort = 'cht-subs-sort'
const storageWinnerAgain = 'cht-subs-winner-again'